CKEDITOR.dialog.add("bootstrapTabsDialog",function(c){return{title:c.lang.bootstrapTabs.dialogTitle,minWidth:310,minHeight:280,contents:[{id:"tab-basic",label:c.lang.bootstrapTabs.tabBasicLabel,elements:[{type:"html",html:c.lang.bootstrapTabs.infoHtml},{type:"text",id:"tab-set-title",label:c.lang.bootstrapTabs.tabSetTitleLabel,validate:CKEDITOR.dialog.validate.notEmpty(c.lang.bootstrapTabs.invalidTabSetTitle),setup:function(a){a=a.data("tab-set-title");this.setValue(a)}},{type:"select",id:"number-of-tabs",
label:c.lang.bootstrapTabs.numberOfTabsLabel,"default":4,items:[["2"],["3"],["4"],["5"],["6"],["7"],["8"],["9"]],validate:CKEDITOR.dialog.validate.notEmpty(c.lang.bootstrapTabs.invalidNumberOfTabs),setup:function(a){a=a.find(".tab button").count();this.setValue(a)}},{type:"html",html:'\x3chr style\x3d"display: block;position: relative;padding: 0;margin: 8px auto;width: 100%;max-height: 0;font-size: 1px;line-height: 0;clear: both;border: none;border-top: 1px solid #aaaaaa;border-bottom: 1px solid #ffffff;"/\x3e'},
{type:"select",id:"tab-to-remove",label:c.lang.bootstrapTabs.removeTabLabel,"default":c.lang.bootstrapTabs.removeTabDefault,items:[[c.lang.bootstrapTabs.removeTabDefault]],setup:function(a){this.clear().add(c.lang.bootstrapTabs.removeTabDefault);a=a.findOne(".tab").find("button");for(i=0;i<a.count();i++)this.add(a.getItem(i).getText())}},{type:"select",id:"tab-to-select",label:c.lang.bootstrapTabs.selectTabLabel,"default":c.lang.bootstrapTabs.selectTabDefault,items:[[c.lang.bootstrapTabs.selectTabDefault]],
setup:function(a){this.clear().add(c.lang.bootstrapTabs.selectTabDefault);a=a.findOne(".tab").find("button");for(i=0;i<a.count();i++)this.add(a.getItem(i).getText())}},{type:"select",id:"default-open",label:c.lang.bootstrapTabs.defaultOpenTabLabel,"default":c.lang.bootstrapTabs.defaultOpenTab,items:[[c.lang.bootstrapTabs.defaultOpenTab]],setup:function(a){this.clear().add(c.lang.bootstrapTabs.defaultOpenTab);a=a.findOne(".tab").find("button");for(i=0;i<a.count();i++)this.add(a.getItem(i).getText())}}]}],
onShow:function(){var a=c.getSelection().getStartElement();a&&(ascendant=a.getAscendant(function(a){return a instanceof CKEDITOR.dom.document?!1:a.hasClass("tabs")}));ascendant?(this.insertMode=!1,a=ascendant):this.insertMode=!0;this.element=a;this.insertMode||this.setupContent(a)},onOk:function(){var a=this.getValueOf("tab-basic","number-of-tabs"),f=this.getValueOf("tab-basic","tab-set-title"),k=this.getValueOf("tab-basic","tab-to-remove");tabToSelect=this.getValueOf("tab-basic","tab-to-select");
defaultOpen=this.getValueOf("tab-basic","default-open");if(this.insertMode){e=CKEDITOR.dom.element.createFromHtml('\x3cdiv class\x3d"tabs"\x3e\x3cdiv class\x3d"tab"\x3e\x3c/div\x3e\x3cdiv class\x3d"tab-content"\x3e\x3c/div\x3e\x3c/div\x3e');for(b=1;b<=a;b++)appendTabToElement(c,this,e,a,b);c.insertElement(e)}else{var e=this.element,g=e.find(".tab button.tab-link").count();e.data("tab-set-title");for(var h=e.findOne("div.tab"),m=e.findOne("div.tab-content"),d=h.find("button"),l=m.find("div.tab-panel"),
b=0;b<d.count();b++)d.getItem(b).hasAttribute("id")&&d.getItem(b).removeAttribute("id"),defaultOpen===d.getItem(b).getText()&&d.getItem(b).setAttribute("id","defaultOpen");for(b=0;b<d.count();b++)d.getItem(b).hasClass("active")&&d.getItem(b).removeClass("active"),l.getItem(b).hasClass("active")&&l.getItem(b).removeClass("active"),tabToSelect===d.getItem(b).getText()&&(d.getItem(b).addClass("active"),l.getItem(b).addClass("active"));for(b=0;b<d.count();b++)k===d.getItem(b).getText()&&d.count()===l.count()&&
(d.getItem(b).remove(),l.getItem(b).remove());if(a>g){h.findOne(".active").removeClass("active");m.findOne(".active").removeClass("active");for(var b=g+1;b<=a;b++)appendTabToElement(c,this,e,a,b)}}e.data("tab-set-title",f);e.addClass(f)}}});
function appendTabToElement(c,a,f,k,e){a=a.getValueOf("tab-basic","tab-set-title");var g="Tab "+e,h=(a+" "+g).replace(/(\W+|\s+|_|-+)/g,"-").replace(/-+/g,"-").toLowerCase();c='\x3cdiv class\x3d"tab-panel" data-id\x3d"'+h+'"\x3e'+('\x3cdiv class\x3d"tab-panel-content"\x3e'+g+" Content\x3c/div\x3e")+"\x3c/div\x3e";a=new CKEDITOR.dom.element.createFromHtml('\x3cbutton type\x3d"button" class\x3d"tab-link" data-parent-title\x3d"'+a+'" data-id\x3d"'+h+'" onclick\x3d"openTab(event, \''+h+"')\"\x3e"+g+" Name\x3c/button\x3e");
c=new CKEDITOR.dom.element.createFromHtml(c);e==k&&(a.addClass("active"),c.addClass("active"));k=f.findOne("div.tab");f=f.findOne("div.tab-content");k.append(a);f.append(c)};