sudo: false

dist: trusty

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  include:
    - php: '5.3'
      dist: precise

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  # PHP_CodeSniffer
  - curl -L -o phpcs.phar https://github.com/squizlabs/PHP_CodeSniffer/releases/download/2.9.1/phpcs.phar
  # PHPUnit - manually download old version so that it works on PHP 7
  - curl -L -o phpunit.phar https://phar.phpunit.de/phpunit-4.8.35.phar
  # Basic config required for PHPUnit
  - cp ilya-tests/phpunit-ilya-config.php ilya-config.php

script:
  # PHP_CodeSniffer
  - php phpcs.phar --report=emacs --extensions=php --standard=ilya-tests/phpcs/ruleset.xml .
  # PHPUnit
  - php phpunit.phar --bootstrap ilya-tests/autoload.php ilya-tests
